"""add_game

Revision ID: 5c1aaee93609
Revises: cc1c4ebe00e4
Create Date: 2024-02-20 19:44:59.077901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1aaee93609'
down_revision: Union[str, None] = 'cc1c4ebe00e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=False),
    sa.Column('winner_rating_before', sa.SmallInteger(), nullable=False),
    sa.Column('winner_income', sa.SmallInteger(), nullable=False),
    sa.Column('winner_rating_after', sa.SmallInteger(), nullable=False),
    sa.Column('loser_id', sa.BigInteger(), nullable=False),
    sa.Column('loser_rating_before', sa.SmallInteger(), nullable=False),
    sa.Column('loser_income', sa.SmallInteger(), nullable=False),
    sa.Column('loser_rating_after', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
